language: php

dist: bionic

php:
  - 7.3
  - 7.4
  - 8.0
  - 8.1

env:
  global:
    - XDEBUG_MODE=coverage

before_script:
  - pwd
  - export cwd=`pwd`
  - composer self-update
  - cd ..
  - pwd
  - git clone -b 3.x https://github.com/kenjis/ci-app-for-ci-phpunit-test.git
  - cd ci-app-for-ci-phpunit-test
  - rm application/tests/_ci_phpunit_test
  - composer update
  - mv vendor/kenjis/ci-phpunit-test vendor/kenjis/ci-phpunit-test.tmp
  - mv "$cwd" vendor/kenjis/ci-phpunit-test
  - php install.php
  - git checkout -- application/tests/Bootstrap.php

script:
  - cd application/tests
  - ../../vendor/bin/phpunit --coverage-text

after_script:
  - cd ../..
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then php vendor/bin/coveralls -v; fi
